#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Takuto Irie
# SPDX-License-Identifier: BSD-3-Clause

import sys

for line in sys.stdin:
    n = int(line)
    #print(f"{n}の約数は:")

    for i in range(1, n + 1):
        if n % i == 0:
            print(i, end=" ")
