name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Make scripts executable
      run: |
        chmod +x divisors
        chmod +x test.bash

    - name: Run tests for divisors
      run: bash -xv ./test.bash
    #- name: All test
      #run: bash -xv ./test.bash
